---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hypershift-addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hypershift-addon-manager-sa
    namespace: default
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hypershift-addon-manager-sa
  namespace: default
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hypershift-addon-manager
  namespace: default
  labels:
    app: hypershift-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypershift-addon-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hypershift-addon-manager
    spec:
      restartPolicy: Always
      serviceAccountName: hypershift-addon-manager-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: hypershift-addon-agent
          image: 'quay.io/ianzhang366/hypershift-addon-operator:latest'
          args:
            - ./hypershift-addon
            - manager
            - '--namespace=open-cluster-management'
          imagePullPolicy: Always
      serviceAccount: hypershift-addon-manager-sa
