# permissions for end users to edit hypershiftdeployment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .SpokeRolebindingName }}
rules:
- apiGroups:
  - apps/v1
  resources:
  - deployment
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1
  resources:
  - secret
  - configmap
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io/v1
  resources:
  - CustomResourceDefinition
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - config.openshift.io/v1
  resources:
  - Infrastructure
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch