---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:klusterlet-work:agent:hypershift'
rules:
  - verbs:
      - get
      - create
      - update
      - patch
      - delete
    apiGroups:
      - hypershift.openshift.io
    resources:
      - hostedclusters
      - nodepools